version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: budgetplan_db
    environment:
      POSTGRES_USER: budgetuser
      POSTGRES_PASSWORD: budgetpass
      POSTGRES_DB: budgetplan
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U budgetuser -d budgetplan"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: budgetplan_backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: budgetuser
      DB_PASSWORD: budgetpass
      DB_NAME: budgetplan
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: budgetplan_frontend
    environment:
      VITE_API_BASE_URL: http://localhost:8080/api/v1
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
